{{/*
  * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
  */}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.instance.ebxPrefix}}-database-secret"
  namespace: "{{ .Values.global.namespace}}"
type: Opaque
data:
  USER: {{ (print .Values.instance.ebxDbUser) | b64enc }}
  PASSWORD:  {{ (print .Values.instance.ebxDbPassword) | b64enc }}


