#
# Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
#

# Global section defines specifics values for an environment (development, qa, production...).
global:
  # ebxImageRegistry is the Docker registry where we pull the EBX image from.
  ebxImageRegistry: ""
  # ebxImageRepository is the EBX image repository
  ebxImageRepository: "ebx"
  # ebxImageTag is The EBX image tag
  ebxImageTag: ""
  # registrySecret that contains the credentials used to connect to the Docker registry.
  imageRegistrySecret: ""
  # namespace where the EBX instance will be deployed
  namespace: "ebx"
  # hostname of the kubernetes server host
  hostname: ""
  # scheme define the protocol of the kubernetes server (default value is https)
  scheme: "https"

# Instance section defines specifics values for the ebx instance
instance:
  # ebxPrefix is the prefix name used for every kubernetes object of the instance (Pod, Service,
  # Ingress...)
  ebxPrefix: ""
  # ebxUser is the username used to connect to the ebx instance (default value is admin)
  ebxUser: "admin"
  # ebxPassword is the password used to connect to the ebx instance
  ebxPassword: ""
  # cpu number allocate to the container (default value is 2)
  cpu: 2
  # memory is the container memory limit allocate to the container (default value is 2Gi)
  memory: "2Gi"
  # storageClass used to claim volumes
  storageClass : "microk8s-hostpath"
  # dataVolumeStorageClaim is the amount of disk space of the PersistentVolume requested by the ebx
  # instance to store it's data
  dataVolumeStorageClaim: "20Gi"
  # logsVolumeStorageClaim is the amount of disk space requested by the PersistentVolumeClaim for
  # the data of the ebx instance
  logsVolumeStorageClaim: "2Gi"

# Ingress section defines specifics values for traffic routing rules of the Ingress resource
ingress:
  # className is the name of the chosen ingress-controller
  className: "nginx"
  # tlsSecret that contains the self-signed certificate and private key
  tlsSecret: ""
  # hostRuleDefied modify the syntax of the ingress according to this value. (default value is true)
  # If set to true, an host must be defined.
  hostRuleDefined: "true"
  # annotations to configure the ingress resource
  annotations:
  # Annotations for AZURE (AKS Cluster using TLS) https://learn.microsoft.com/en-us/azure/aks/ingress-tls?tabs=azure-cli
  # nginx.ingress.kubernetes.io/use-regex: "true"
  # cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # TODO comment

# Database section defines specifics values for the database connectivity
database:
  # name is the database name
  name:
  # user is the database user
  user:
  # pwd is the database password
  pwd:
  # host is the database host
  host:
  # port is the database port
  port:
  # type is the database type (postgresql, sqlserver, oracle etc...  check the ... doc) TODO
  type:

  # Microsoft Azure SQL database (the following values will be use only if database.type is eq to azure.sql)
  encrypt: "true"
  trustServerCertificate: "false"
  hostNameInCertificate: "*.database.windows.net"




