{{/*
  * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
  */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.ebx.prefix}}"
  namespace: "{{ .Values.global.namespace}}"
  labels:
    app: "{{ .Values.ebx.prefix}}-app"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.ebx.prefix}}-app"
  replicas: 1
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "{{ .Values.ebx.prefix}}-app"
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: "{{ .Values.ebx.prefix}}-instance-pod"
          image: "{{ .Values.global.ebxImage}}"
          ports:
            - containerPort: 8080
          env:
            - name: EBX_DB_FACTORY
              value: "{{ .Values.ebx.databaseType}}"
            - name: EBX_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Values.ebx.prefix}}-databases-drivers-url-configmap"
                  key: "{{ .Values.ebx.databaseType}}"
            - name: EBX_ROOT_PATH
              value: "/{{ .Values.ebx.prefix}}"
            - name: EBX_IS_SECURED
              value: "true"
            - name: EBX_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.ebx.prefix}}-database-secret"
                  key: "USER"
            - name: EBX_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.ebx.prefix}}-database-secret"
                  key: "PASSWORD"
            - name: EBX_FLA_DISABLED # TODO add in Readme, mandatory si pas de repo init
              value: "true"
            - name: EBX_REST_AUTHENTICATION_BASIC
              value: "true"
            - name: EBX_INSTALL_ADMIN_LOGIN
              value: "{{ .Values.ebx.adminLogin}}"
            - name: EBX_INSTALL_ADMIN_PASSWORD
              value: "{{ .Values.ebx.adminPassword}}"
          resources:
            limits:
              memory: "{{ .Values.ebx.memory}}"
              cpu: {{ .Values.ebx.cpu}}
            requests:
              memory: "{{ .Values.ebx.memory}}"
              cpu: {{ .Values.ebx.cpu}}
          volumeMounts:
            - mountPath: "/usr/share/ebx/data"
              name: "{{ .Values.ebx.prefix}}-persistent-storage-data"
            - mountPath: "/usr/share/ebx/logs"
              name: "{{ .Values.ebx.prefix}}-persistent-storage-logs"
      {{- if .Values.global.ebxImageRegistrySecret }}
      imagePullSecrets:
        - name: "{{ .Values.global.ebxImageRegistrySecret}}"
      {{- end }}
      initContainers:
        - name: sysctl
          image: busybox
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144 && ulimit -n 512000']
      volumes:
        - name: "{{ .Values.ebx.prefix}}-persistent-storage-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.ebx.prefix}}-pv-local-claim-data"
        - name: "{{ .Values.ebx.prefix}}-persistent-storage-logs"
          persistentVolumeClaim:
            claimName: "{{ .Values.ebx.prefix}}-pv-local-claim-logs"