{{- if eq .Values.samples.isOpenShift "true" }}
{{/*
    * Copyright Cloud Software Group, Inc. 2023.
    */}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: "{{ .Values.ebx.prefix}}-app"
  name: "{{ .Values.ebx.prefix}}-ebx"
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: "{{ .Values.ebx.prefix}}-ebx"
{{- end }}
