{{/*
  * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
  */}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.ebx.prefix}}-ebx-logon"
  namespace: "{{ .Values.global.namespace}}"
type: Opaque
data:
  LOGIN: {{ (print .Values.ebx.adminLogin) | b64enc }}
  PASSWORD:  {{ (print .Values.ebx.adminPassword) | b64enc }}


