{{/*
  * Copyright Cloud Software Group, Inc. 2023.
  */}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.ebx.prefix}}-ebx-db"
  namespace: "{{ .Values.global.namespace}}"
type: Opaque
data:
  USER: {{ (print .Values.ebx.databaseUser) | b64enc }}
  PASSWORD:  {{ (print .Values.ebx.databasePwd) | b64enc }}


