{{- if eq .Values.samples.postgresqlDynamicProvisioningEnable "true" }}
{{/* * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved. */}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.ebx.prefix}}-ebx-psql-srv"
  namespace: "{{ .Values.global.namespace}}"
type: Opaque
data:
  USER: {{ (print .Values.postgresServer.user) | b64enc }}
  PASSWORD:  {{ (print .Values.postgresServer.pwd) | b64enc }}
  DATABASE: {{ (print .Values.postgresServer.database) | b64enc }}
{{- end }}