{{/*
   * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
   */}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ebx.prefix}}-ebx"
  namespace: "{{ .Values.global.namespace}}"
  labels:
    app: "{{ .Values.ebx.prefix}}-ebx"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.ebx.prefix}}-app"
  ports:
    - name: 8080-tcp
      protocol: "TCP"
      port: 8080
      targetPort: 8080
