#
# Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
#

# Global section defines specifics values for an environment (development, qa, production...).
global:
  # ebxImage is the ebx container edition image URL
  ebxImage:
  # ebxInitImage is the ebx-init image URL # TODO add in Readme
  ebxInitImage:
  # ebxImageRegistrySecret that contains the credentials used to connect to the registry that host the ebx image.
  ebxImageRegistrySecret: "" # (Optional)
  # namespace where the EBX pod will be deployed
  namespace: "ebx"
  # hostname of the kubernetes server host
  hostname: "" # (Optional)
  # scheme defines the http protocol of the kubernetes server (default value is https, valid values are http and https)
  scheme: "https" # TODO Review this, is it useful ? only seen in NOTES.txt

# EBX section defines specifics values for the ebx instance
ebx:
  # prefix is the prefix name used for every kubernetes object of the instance (Pod, Service,
  # Ingress...) (Mandatory) TODO
  prefix: ""
  # adminLogin is the username used to connect to the ebx instance (default value is admin)
  adminLogin: "admin" # TODO change to admin in files + # (Optional -> TODO reco de les mettre, mais seront ignoré si le repo est déjà init -> évite de rendre accessible un ebx sans login/mdp)
  # adminPassword is the password used to connect to the ebx instance
  adminPassword: "" # (Optional TODO -> reco de les mettre, mais seront ignoré si le repo est déjà init -> évite de rendre accessible un ebx sans login/mdp)
  # isSecured ... TODO + add in README
  isSecured: "true"
  # flaDisabled... TODO add in Readme, mandatory si pas de repo init
  flaDisabled: "true"
  # restAuthenticationBasic... TODO + add in README
  restAuthenticationBasic: "true"
  # cpu number allocate to the container (default value is 2)
  cpu: 2
  # memory is the container memory limit allocate to the container (default value is 2Gi)
  memory: "2Gi"
  # storageClass used to claim volumes (will take default storageClass if no value is specified)
  storageClass : ""
  # dataVolumeStorageClaim is the amount of disk space of the PersistentVolume requested by the ebx
  # instance to store it's data
  dataVolumeStorageClaim: "20Gi"
  # logsVolumeStorageClaim is the amount of disk space requested by the PersistentVolumeClaim for
  # the data of the ebx instance
  logsVolumeStorageClaim: "2Gi"

  # databaseName is the database name
  databaseName:
  # databaseUser is the database user
  databaseUser:
  # databasePwd is the database password
  databasePwd:
  # databaseHost is the database host
  databaseHost:
  # databasePort is the database port
  databasePort:
  # databaseType is the database type (postgresql, sqlserver, oracle etc...  check the ... doc) TODO
  databaseType:

  # SQL databases (the following values will be use only if database.type is eq to sqlserver or azure.sql)
  # databaseEncrypt is a property for jdbc sql connection (set to true that specify that the SQL Server uses TLS encryption)
  databaseEncrypt: "true" # (Optional)
  #  databaseTrustServerCertificate is a property for jdbc sql connection (set to true that specify that the driver doesn't
  # validate the server TLS/SSL certificate.)
  #databaseTrustServerCertificate: "false"
  # databaseHostNameInCertificate is the host name to be used to validate the SQL Server TLS/SSL certificate.
  #databaseHostNameInCertificate: "*.database.windows.net"
  # databaseLoginTimeout is the number of seconds the driver should wait before timing out a failed connection
  #databaseLoginTimeout: 30
  #TODO above

# Ingress section defines specifics values for traffic routing rules of the Ingress resource
ingress:
  # className is the name of the chosen ingress-controller
  className: "nginx"
  # tlsSecret that contains the self-signed certificate public and private key
  tlsSecret: "" # (Optional)
  # hostRuleDefied modify the syntax of the ingress according to this value. (default value is true)
  # If set to true, an host must be defined.
  hostRuleDefined: "true"
  # annotations to configure the ingress resource
  annotations:
  # pathRegex will complete the path ingress path field. For example with the default value, the final path will be of
  # the form "/{{ .Values.ebx.prefix}}/ebx.*" .
  # This value may change depending on the type of the ingress controller.
  pathRegex: ".*"
  # pathType is pathType of the ingress.
  pathType:  "Prefix"

# postgresServer section defines specifics values for the postgresServer connectivity
postgresServer:
  #  database is the postgres server master database name
  database: ""
  # user is the postgres server master database name
  user: "postgres"
  #  pwd is the postgres server master database name
  pwd: ""


