#
# Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
#

# Global section defines specifics values for an environment (development, qa, production...).
global:
  # ebxImageRegistry is the Docker registry where we pull the EBX image from.
  ebxImageRegistry: ""
  # ebxImageRegistry is the Docker registry where we pull the EBX-INIT image from.
  ebxInitImageRegistry: ""
  # ebxImageRepository is the EBX image repository
  ebxImageRepository: "ebx"
  # ebxImageTag is The EBX image tag
  ebxImageTag: ""
  # ebxInitImageRepository is the EBX-INIT image repository
  ebxInitImageRepository: "ebx-init"
  # ebxImageTag is The EBX image tag
  ebxInitImageTag: ""
  # registrySecret that contains the credentials used to connect to the Docker registry.
  imageRegistrySecret: ""
  # namespace where the EBX instance will be deployed
  namespace: "ebx"
  # hostname of the kubernetes server
  hostname: ""
  # scheme define the protocol of the kubernetes server (default value is https)
  scheme: "https"

# Instance section defines specifics values for the ebx instance
instance:
  # ebxPrefix is the prefix name used for every kubernetes object of the instance (Pod, Service,
  # Ingress...)
  ebxPrefix: ""
  # ebxUser is the username used to connect to the ebx instance (default value is admin)
  ebxUser: "admin"
  # ebxPassword is the password used to connect to the ebx instance
  ebxPassword: ""
  # ebxDatabaseType is the database type used by the ebx instance (override EBX_DB_FACTORY value of
  # the ebx container)
  ebxDatabaseType: "postgresql"
  # ebxDatabase is the database name used by the ebx instance
  ebxDatabase: ""
  # ebxDbUser is the database user used by the ebx instance
  ebxDbUser: ""
  # ebxDbPassword is the database password used by the ebx instance
  ebxDbPassword: ""

  # cpu number allocate to the container (default value is 2)
  cpu: 2
  # memory is the container memory limit allocate to the container (default value is 2Gi)
  memory: "2Gi"

  # storageClass used to claim volumes
  storageClass : "default"
  # dataVolumeStorageClaim is the amount of disk space of the PersistentVolume requested by the ebx
  # instance to store it's data
  dataVolumeStorageClaim: "20Gi"
  # logsVolumeStorageClaim is the amount of disk space requested by the PersistentVolumeClaim for
  # the data of the ebx instance
  logsVolumeStorageClaim: "2Gi"

# ingress section defines specifics values for traffic routing rules of the Ingress resource
ingress:
  # className is the name of the chosen ingress-controller
  className: "nginx"
  # tlsSecret that contains the self-signed certificate and private key
  tlsSecret: ""
  # hostRuleDefied modify the syntax of the ingress according to this value. (default value is true)
  # If set to true, an host must be defined.
  hostRuleDefined: "true"
  # annotations to configure the ingress resource
  annotations:
  # Annotations for AZURE (AKS Cluster using TLS) https://learn.microsoft.com/en-us/azure/aks/ingress-tls?tabs=azure-cli
  # nginx.ingress.kubernetes.io/use-regex: "true"
  # cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# postgresServer section defines specifics values of the PostgreSQL Server
postgresServer:
  # databaseName is the PostgreSQL master database name
  databaseName: ""
  # databaseUser is the PostgreSQL master database user
  databaseUser: "postgres"
  # databasePassword is the PostgreSQL master database password
  databasePassword: ""
  # host of the PostgreSQL server
  host: ""
  # port where PostgreSQL can be accessed
  port: 5432

