{{/*
  * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
  */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.ebx.prefix}}-pv-local-claim-data"
  namespace: "{{ .Values.global.namespace}}"
  labels:
    app: "{{ .Values.ebx.prefix}}-app"
spec:
  {{- if .Values.ebx.storageClass }}
  storageClassName: "{{ .Values.ebx.storageClass}}"
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.ebx.dataVolumeStorageClaim}}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.ebx.prefix}}-pv-local-claim-logs"
  namespace: "{{ .Values.global.namespace}}"
  labels:
    app: "{{ .Values.ebx.prefix}}-app"
spec:
  {{- if .Values.ebx.storageClass }}
  storageClassName: "{{ .Values.ebx.storageClass}}"
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.ebx.logsVolumeStorageClaim}}"

