
global:
  namespace: "ebx"
  ebxImage: "<your.registry.com/ebx:6.1.0>"
  hostname: "<your.dns.azure.com>"

ebx:
  prefix: "aks-sql"
  adminPassword: '<?Y0urP4ssWord!>'
  isSecured: "true"
  databaseName: "<ebx db name>"
  databaseUser: "<ebx db user>"
  databasePwd: "<ebx db password>"
  databaseHost: "<ebx db host>"
  databasePort: "<ebx db port>"
  databaseType: "sqlserver"
  databaseEncrypt: "false" # (Optional)
  databaseTrustServerCertificate: "false" # (Optional)
  databaseHostNameInCertificate: "*.database.windows.net" # (Optional)
  databaseLoginTimeout: 30 # (Optional)

ingress:
  tlsSecret: "letsencrypt-tls-secret"
  hostRuleDefined : "true"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "<your ClusterIssuer name>"
