
global:
  namespace: "ebx"
  ebxImage: "<your.registry.com/ebx:ebx-image-tag>"
  hostname: "<your.dns.com>"

ebx:
  prefix: "microk8s-postgresql"
  adminPassword: '<?Y0urP4ssWord!>'
  isSecured: "true"
  databaseName: "<ebx db name>"
  databaseUser: "<ebx db user>"
  databasePwd: "<ebx db password>"
  databaseHost: "<ebx db host>"
  databasePort: "<ebx db port>"
  databaseType: "postgresql>"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
