#
# Copyright Cloud Software Group, Inc. 2023.
#
global:
  namespace: "ebx"
  ebxImage: "<your.registry.com/ebx:ebx-image-tag>"
  hostname: "<your.dns.com>"

ebx:
  prefix: "microk8s-sql"
  adminPassword: '<?Y0urP4ssWord!>'
  isSecured: "true"
  databaseName: "<ebx db name>"
  databaseUser: "<ebx db user>"
  databasePwd: "<ebx db password>"
  databaseHost: "<ebx db host>"
  databasePort: "<ebx db port>"
  databaseType: "sqlserver"
  databaseEncrypt: "false" # (Optional)
  databaseTrustServerCertificate: "false" # (Optional)
  databaseHostNameInCertificate: "*.database.windows.net" # (Optional)
  databaseLoginTimeout: 30 # (Optional)

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
