
global:
  namespace: "ebx"
  ebxImage: "brm.orchestranetworks.com:5001/ebx:6.1.0"
  hostname: "k8s.orchestranetworks.com"

ebx:
  prefix: "postgresql"
  adminPassword: '<?Y0urP4ssWord!>'
  isSecured: "true"
  databaseName: "<ebx db name>"
  databaseUser: "<ebx db user>"
  databasePwd: "<ebx db password>"
  databaseHost: "<ebx db host>"
  databasePort: "<ebx db port>"
  databaseType: "postgresql>"

ingress:
  hostRuleDefined : "false"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
