{{/*
  * Copyright Cloud Software Group, Inc. 2000-2023. All rights reserved.
  */}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.instance.ebxPrefix}}-database-secret"
  namespace: "{{ .Values.global.namespace}}"
type: Opaque
data:
  USER: {{ (print .Values.database.user) | b64enc }}
  PASSWORD:  {{ (print .Values.database.pwd) | b64enc }}


